CREATE TABLE `t_stake_wallet_ops` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) NOT NULL,
  `currency` int(11) NOT NULL,
  `account_type` int(11) NOT NULL,
  `op` int(11) NOT NULL,
  `amount_ev` bigint(20) DEFAULT '0',
  `fill_amount_rq` bigint(20) DEFAULT '0',
  `revert_amount_rq` bigint(20) DEFAULT '0',
  `vid` bigint(20) DEFAULT '0',
  `biz_code` int(11) NOT NULL,
  `request_key` varchar(128) DEFAULT NULL,
  `status` int(11) DEFAULT '0',
  `ack_code` int(11) DEFAULT '0',
  `related_req_id` bigint(20) DEFAULT '0',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sha_request_key` varchar(42) NOT NULL DEFAULT '',
  `request_cnt` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `iu_bizcode_shareqkey` (`biz_code`,`sha_request_key`),
  KEY `Idx_sha_key` (`sha_request_key`),
  KEY `Idx_uid_reqkey` (`user_id`,`request_key`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11674254 DEFAULT CHARSET=utf8;